### PR TITLE
introduce Subject replacing CompatibilitySubject and RegisterSubject

### PR DESCRIPTION
**Pull request by chriskn**
This change introduces the data class `Subject` replacing the identical data classes `CompatibilitySubject` and `RegisterSubject` and therefore allowing the reuse of subject definitions in the compatibility and register block. 

This change is breaking if `CompatibilitySubject` or `RegisterSubject` were directly used, but I assume most users used the `subject()` DSL in the `register{}` and `compatibility{}` blocks instead, which is not affected by this change. 

@ImFlog please let me know what you think. 

See [issue](https://github.com/ImFlog/schema-registry-plugin/issues/116)

### CODE REVIEW

**Review by ImFlog — COMMENTED** [review]
Going quickly through th PR, I don't think we want to break compatibility.
I think we can create a class Subject, that CompatibilitySubject and RegisterSubject) would inherit from and then add a new method in each extension that would add the subject to the correct list.
That would not break anything (and may simplify a bit the code).
WDYT ?

**Comment by ImFlog** [comment]
Hello @chriskn and sorry for the delay.

I finally had time to look into this more deeply. I missread your comment, and while going through the code it indeed does not break anything if people don't directly use the Subjects (and as you said it's probably not the case).
I think your code is great but I am not sure about the naming of the `Subject` class.
Has it will become usable in the gradle files I would love to find something that represent the fact that it's for register and compatibility but I have no idea 😅 

To finish this PR (I can help if needed):
[ ] Add some explanation in the README
[ ] Update the examples ?
[ ] Find the right name ?

Once again thank you for providing this MR and if needed I can do the rest 🙏

**Comment by chriskn** [comment]
Hi @ImFlog, sorry for the late response. If you find the time, help would be appreciated. Otherwise, I can have a look into it in some days, but a suggestion for the Subject name would be needed.

**Comment by ImFlog** [comment]
I've pushed the mentioned changes.
If you can give it a try and tell me if it works for your use case that would be great.
And if it does, I will merge (probably next week) and release a new version.

**Comment by chriskn** [comment]
Thank you! LGTM

**Pull request merged**
