### PR TITLE
Support for confluent 5.5: Avro / Json / Protobuf

### LINKED ISSUE #39: Protobuf support
Any plans to support protobuf and json schema (from confluent platform 5.5+)?

### PR DESCRIPTION
**Pull request by ImFlog**
This will fix #39 (when finished).
Currently Avro support still works (using deprecated endpoints).

Using `ParsedSchema` instead of `Schema` should suffice for confluent 5.5 usage.

Checklist:
- [x] Download
- [x] Register
- [x] Compatibility
- [x] Config
- [x] Update README with new extensions
- [x] Update examples
- [x] Test with Json and Protobuf
- [x] Update examples with JSON and Protobuf
- [x] Create release (specify that the 1.0.0 is the first to support Avro + Json + Protobuf) and that it contains a breaking change.

### CODE REVIEW

**Comment by ImFlog** [comment]
Implementation nearly done, still need to do some cleanup and update documentation.

**Comment by clatko-globe** [comment]
Appears that the CachedSchemaRegistryClient needs to be passed a list of schema providers for this to work. If none is passed, a default list containing only Avro is used.

**Comment by ImFlog** [comment]
Good catch @clatko-globe ! I still have to add Json and Protobuf to the tests so I I did not have errors in my current developments :)
Planning to start polishing later today :)

**Comment by clatko-globe** [comment]
added a basic pr - https://github.com/ImFlog/schema-registry-plugin/pull/45 - off this branch to add the supported providers. my tests with protobuf appear to work ok.

**Comment by ImFlog** [comment]
@clatko-globe thanks for the help, I already did the fix when you published your PR, sorry for the time spent.
Did you manage to make it work with protobuf ? I am planning to release a 1.0.0-SNAPSHOT version to simplify the /example directory update.
I need to improve the tests but I think it could be useful to release this so people can give feedback about the usage.

**Comment by clatko-globe** [comment]
I started using the 1.0.0-SNAPSHOT and this works with protobuf as well.

I am having issues declaring dependencies however. With the following format:

`    register {
        subject("test-service-proto", "proto/io/iomega/service/email/proto/user.proto", "PROTOBUF", ['proto/io/iomega/service/email/proto/company.proto'])
    }
`
I get the error:
No signature of method: build_avro_8zm84osbbavlcetf8gyewxus8.schemaRegistry() is applicable for argument types: (build_avro_8zm84osbbavlcetf8gyewxus8$_run_closure8) values: [build_avro_8zm84osbbavlcetf8gyewxus8$_run_closure8@c301c1be]

I cannot see why this is failing as I clearly see the signature here - https://github.com/ImFlog/schema-registry-plugin/pull/44/files#diff-2cd2ad109510643b87f80c97d366c444R16

**Comment by ImFlog** [comment]
One of the breaking changes from this update is that the dependencies are not in the same format.
You need to do something like this:
```groovy
register { 
    subject("test-service-proto", "proto/io/iomega/service/email/proto/user.proto", "PROTOBUF", [new SchemaReference('company', 'company', 1)
    ])
}
```
Where the SchemaReference contains the subject where your schema is registered, the actual type you want from this schema and the version. At least that's what I understand from the new API.

**Comment by clatko-globe** [comment]
Just a heads up. I got this to work. The proper syntax is (notice the full path with prepended `proto` in second arg):

```
    register {
        subject("io/iomega/service/email/proto/user.proto", "proto/io/iomega/service/email/proto/user.proto", "PROTOBUF",
        new SchemaReference('io/iomega/service/email/proto/company.proto', 'io/iomega/service/email/proto/company.proto', 1),
        new SchemaReference('google/protobuf/timestamp.proto', 'google/protobuf/timestamp.proto', 1))
    }
```

The user proto looks like:

```
syntax = "proto3";
package proto;
import "google/protobuf/timestamp.proto";
import "io/iomega/service/email/proto/company.proto";

message User {
  Company company = 1;
  google.protobuf.Timestamp timestamp = 2;
}
```

The naming convention may seem a bit odd, but am following google on this.

I understand the concerns around the SchemaReference. I'm also concerned about hardcoding a version id. Perhaps the varargs should be intercepted and instantiated within `RegisterSubjectExtension.kt`. A version lookup could also be done.

**Comment by ImFlog** [comment]
The second arg is the relative path to the gradle root directory, I suppose yours looks like
```
dir/
  build.gradle
  proto/
    io/
      ...
        user.proto
```
Am I right ?

About the SchemaReference version we could indeed fetch the last version from the registry if not specified.
About the varargsm I guess that's the idea but I would like to avoid people to rely on specific import (like it's working currently). Maybe tuples could work. Will try this later today I think.

**Comment by ImFlog** [comment]
I've just added testContainers to the tests to remove the need to use Wiremock, still need to find a way to handle authentication when spawning the Schema-Registry container. This will fix #42.
After that I will add parameterized tests to handle Protobuf and JSON schema and that should be it !

**Comment by clatko-globe** [comment]
You are correct about the directory structure. I've updated with the new syntax and will create a PR for examples one I have everything sorted.

**Comment by ImFlog** [comment]
The last commit contains a working register with a dependency in Protobuf. I managed to make it work without the need to have a subject that looks like the directory structure (see https://github.com/ImFlog/schema-registry-plugin/pull/44/commits/f719360d1db3012a0f01f472703839de41ce0f69). I struggled a lot with Protobuf but your previous comment helped me @clatko-globe :)
I will try to implement the compatibility tests today and the only thing left will be the example folder.

**Comment by clatko-globe** [comment]
created protobuf example - https://github.com/ImFlog/schema-registry-plugin/pull/47

**Pull request merged**
