### PR TITLE
Add schema dependency resolution

### LINKED ISSUE #12: Handle dependencies between avsc files for register
When we register new schemas, sometimes they refer to other schemas.
Typical example is for a user record that can contain an address record for example.
A potential implementation is available here : https://github.com/ImFlog/schema-registry-plugin/pull/11

### PR DESCRIPTION
**Pull request by ImFlog**
Intent to fix #12.

@oasalonen, I spent some time looking for something better than a plain list and thought that a Triple might be better.
Like this we know directly that what we send is the second of the triple and that the rest is here as dependencies. WDYT ?
Anyway this looks a lot like what you did in the first place.

### CODE REVIEW

**Comment by oasalonen** [comment]
Looks good. I would suggest one improvement to the ordering of the dependencies using the user->address->street example. If I understood correctly, right now the syntax would expect you to declare "user.avsc", ["street.avsc", "address.avsc"]. However, the dependency chain would be 'user depends on address depends on street' and as a user I would expect to write them in that order. 

So how about you reverse the processing of the dependencies in the list, going from tail to head of the list so user's can write the chain as "user.avsc", ["address.avsc", "street.avsc"]?

**Comment by ImFlog** [comment]
This is a good idea, I'm doing the changes.

**Comment by ImFlog** [comment]
The version 0.4.0 embedded this new feature.

**Comment by oasalonen** [comment]
I migrated back to your plugin release and the feature works. Thanks for integrating it!

**Pull request merged**
