### PR TITLE
Fixing master build

### PR DESCRIPTION
**Pull request by StephanePaulus**
I was unaware that normalisation would change between Kafka version. Not sure if you like the fix I did.

### CODE REVIEW

**Comment by StephanePaulus** [comment]
After this PR is merged, when do you think you will be able to make a release? Are SNAPSHOT builds pushed to the gradle-plugin-registry?

**Comment by ImFlog** [comment]
SNAPSHOT builds are not release to the gradle plugin portal (not a supported feature).
Hopefully I will try to push a release during the weekend.

**Comment by ImFlog** [comment]
Hello @StephanePaulus.
Planned to release tonight but things didn't work as expected. See https://github.com/ImFlog/schema-registry-plugin/issues/159#issuecomment-1951476185

If by any chance you can try to build a local version (using the `publishToMavenLocal` task) and see if the example directory works with your local version that could help me see if it's only failing on my machine ...

Sorry for the delay anyway 🙇

**Comment by ImFlog** [comment]
Should be available in version 2.0.0 (requires gradle 8).
Sorry for the delay 🙇

**Comment by StephanePaulus** [comment]
@ImFlog I just tried it, and I have errors of missing packages
```
> Could not resolve all files for configuration ':classpath'.
   > Could not find io.confluent:kafka-schema-registry:7.6.0.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/io/confluent/kafka-schema-registry/7.6.0/kafka-schema-registry-7.6.0.pom
     Required by:
         project : > com.github.imflog.kafka-schema-registry-gradle-plugin:com.github.imflog.kafka-schema-registry-gradle-plugin.gradle.plugin:2.0.0 > com.github.imflog:kafka-schema-registry-gradle-plugin:2.0.0
   > Could not find com.github.ImFlog.avro:avro:1.11.2.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/com/github/ImFlog/avro/avro/1.11.2/avro-1.11.2.pom
     Required by:
         project : > com.github.imflog.kafka-schema-registry-gradle-plugin:com.github.imflog.kafka-schema-registry-gradle-plugin.gradle.plugin:2.0.0 > com.github.imflog:kafka-schema-registry-gradle-plugin:2.0.0

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
 ```

**Comment by ImFlog** [comment]
I removed the fat jar things because it caused incompatibilities.
You need to add repositories to your `buildscript` in order to make it work.
Check the README for up to date documentation.

**Pull request merged**
